changed initial guess for optimizer 3 from
0.000223 0.1 0.01, 0.6 0.483 0.4 0.4 0.2 0.04 0.02 0.123 0.3292
error: 188,052.724

to
0.000272 0.169 0.02 1.6 0.483 0.4 0.4 1.75 1.04 0.02 0.031 0.329
error: 177,825.144 (this is from Magnus, who ran the optimizer with no error and converged on these values)

max param changed from
0.0003 0.5 0.1 2.0 100 5 5 5 5 0.02 1 20
to
0.0003 0.5 0.1 2.0 10 5 5 5 5 0.021 1 2
(giving the optimizer constrained parameter sets to avoid errors)